# Generated by Django 3.0.4 on 2020-03-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='order_id',
            new_name='ticket_id',
        ),
    ]
